 version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_test
    ports:
      - "3306:3306"

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: root
      DATABASE_PASSWORD: null
      DATABASE_NAME: database_test
